# Generated by Django 6.0.7 on 2026-08-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_purchaseitem_cost_price_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchaseitem',
            name='unique_product_per_purchase',
        ),
    ]
