# Generated by Django 6.0.7 on 2026-08-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('purchases', '0003_remove_purchaseitem_unique_product_per_purchase'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.UniqueConstraint(fields=('purchase', 'product'), name='unique_product_per_purchase'),
        ),
    ]
