# Generated by Django 6.0.7 on 2026-08-08 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_purchasepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='purchases.purchase'),
        ),
    ]
